alter proc dbo.Download
as
delete INTERBASEDOWNLINK...ASC_MAP
insert into INTERBASEDOWNLINK...ASC_MAP
select * from ASC_MAP

delete INTERBASEDOWNLINK...ASC_TEMPLATES
insert into INTERBASEDOWNLINK...ASC_TEMPLATES
select * from ASC_TEMPLATES

delete INTERBASEDOWNLINK...DATA_FEEDS
insert into INTERBASEDOWNLINK...DATA_FEEDS
select * from DATA_FEEDS

delete INTERBASEDOWNLINK...DICTIONARY
insert into INTERBASEDOWNLINK...DICTIONARY
select * from DICTIONARY

delete INTERBASEDOWNLINK...EXCHANGES
insert into INTERBASEDOWNLINK...EXCHANGES
select * from EXCHANGES

delete INTERBASEDOWNLINK...HOLIDAYS
insert into INTERBASEDOWNLINK...HOLIDAYS
select * from HOLIDAYS

delete INTERBASEDOWNLINK...HOLIDAY_DETAILS
insert into INTERBASEDOWNLINK...HOLIDAY_DETAILS
select * from HOLIDAY_DETAILS

delete INTERBASEDOWNLINK...SESSIONS
insert into INTERBASEDOWNLINK...SESSIONS
select * from SESSIONS

delete INTERBASEDOWNLINK...SESSION_DETAILS
insert into INTERBASEDOWNLINK...SESSION_DETAILS
select * from SESSION_DETAILS

delete INTERBASEDOWNLINK...SETTINGS
insert into INTERBASEDOWNLINK...SETTINGS
select * from SETTINGS

delete INTERBASEDOWNLINK...PORTFOLIO
insert into INTERBASEDOWNLINK...PORTFOLIO
select * from PORTFOLIO

grant EXECUTE on Download to sim

