IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'OPTION_PRICE_TEMP')
   SELECT * INTO OPTION_PRICE_TEMP FROM OPTION_PRICE WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'STD_OPTION_PRICE_TEMP')
   SELECT * INTO STD_OPTION_PRICE_TEMP FROM STD_OPTION_PRICE WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'SECURITY_PRICE_TEMP')
   SELECT * INTO SECURITY_PRICE_TEMP FROM SECURITY_PRICE WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'OPTION_VOLUME_TEMP')
   SELECT * INTO OPTION_VOLUME_TEMP FROM OPTION_VOLUME WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'VOLATILITY_SURFACE_TEMP')
   SELECT * INTO VOLATILITY_SURFACE_TEMP FROM VOLATILITY_SURFACE WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'HISTORICAL_VOLATILITY_TEMP')
   SELECT * INTO HISTORICAL_VOLATILITY_TEMP FROM HISTORICAL_VOLATILITY WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'INDEX_DIVIDEND_TEMP')
   SELECT * INTO INDEX_DIVIDEND_TEMP FROM INDEX_DIVIDEND WHERE 1=2
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE Name = 'ZERO_CURVE_TEMP')
   SELECT * INTO ZERO_CURVE_TEMP FROM ZERO_CURVE WHERE 1=2
GO
TRUNCATE TABLE OPTION_PRICE_TEMP
TRUNCATE TABLE STD_OPTION_PRICE_TEMP
TRUNCATE TABLE SECURITY_PRICE_TEMP
TRUNCATE TABLE OPTION_VOLUME_TEMP
TRUNCATE TABLE VOLATILITY_SURFACE_TEMP
TRUNCATE TABLE HISTORICAL_VOLATILITY_TEMP
TRUNCATE TABLE INDEX_DIVIDEND_TEMP
TRUNCATE TABLE ZERO_CURVE_TEMP
GO


