//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 6/10/2009 10:43:16 AM
namespace TradingScreenApiService
{
    
    /// <summary>
    /// There are no comments for BADBEntities in the schema.
    /// </summary>
    public partial class BADBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new BADBEntities object using the connection string found in the 'BADBEntities' section of the application configuration file.
        /// </summary>
        public BADBEntities() : 
                base("name=BADBEntities", "BADBEntities")
        {
            OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BADBEntities object.
        /// </summary>
        public BADBEntities(string connectionString) : 
                base(connectionString, "BADBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BADBEntities object.
        /// </summary>
        public BADBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "BADBEntities")
        {
            OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for FuturesSymbolMapping in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FuturesSymbolMapping> FuturesSymbolMapping
        {
            get
            {
                if ((_FuturesSymbolMapping == null))
                {
                    _FuturesSymbolMapping = base.CreateQuery<FuturesSymbolMapping>("[FuturesSymbolMapping]");
                }
                return _FuturesSymbolMapping;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FuturesSymbolMapping> _FuturesSymbolMapping;
        /// <summary>
        /// There are no comments for FuturesSymbolMapping in the schema.
        /// </summary>
        public void AddToFuturesSymbolMapping(FuturesSymbolMapping futuresSymbolMapping)
        {
            base.AddObject("FuturesSymbolMapping", futuresSymbolMapping);
        }
    }
    /// <summary>
    /// There are no comments for BADBModel.FuturesSymbolMapping in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BADBModel", Name="FuturesSymbolMapping")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FuturesSymbolMapping : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FuturesSymbolMapping object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="platformId">Initial value of PlatformId.</param>
        /// <param name="platformReceivingSymbolRoot">Initial value of PlatformReceivingSymbolRoot.</param>
        /// <param name="bloombergSymbolRoot">Initial value of BloombergSymbolRoot.</param>
        /// <param name="priceMultiplier">Initial value of PriceMultiplier.</param>
        public static FuturesSymbolMapping CreateFuturesSymbolMapping(long id, string platformId, string platformReceivingSymbolRoot, string bloombergSymbolRoot, decimal priceMultiplier)
        {
            FuturesSymbolMapping futuresSymbolMapping = new FuturesSymbolMapping();
            futuresSymbolMapping.ID = id;
            futuresSymbolMapping.PlatformId = platformId;
            futuresSymbolMapping.PlatformReceivingSymbolRoot = platformReceivingSymbolRoot;
            futuresSymbolMapping.BloombergSymbolRoot = bloombergSymbolRoot;
            futuresSymbolMapping.PriceMultiplier = priceMultiplier;
            return futuresSymbolMapping;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PlatformId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlatformId
        {
            get
            {
                return this._PlatformId;
            }
            set
            {
                this.OnPlatformIdChanging(value);
                this.ReportPropertyChanging("PlatformId");
                this._PlatformId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PlatformId");
                this.OnPlatformIdChanged();
            }
        }
        private string _PlatformId;
        partial void OnPlatformIdChanging(string value);
        partial void OnPlatformIdChanged();
        /// <summary>
        /// There are no comments for Property PlatformReceivingSymbolRoot in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlatformReceivingSymbolRoot
        {
            get
            {
                return this._PlatformReceivingSymbolRoot;
            }
            set
            {
                this.OnPlatformReceivingSymbolRootChanging(value);
                this.ReportPropertyChanging("PlatformReceivingSymbolRoot");
                this._PlatformReceivingSymbolRoot = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PlatformReceivingSymbolRoot");
                this.OnPlatformReceivingSymbolRootChanged();
            }
        }
        private string _PlatformReceivingSymbolRoot;
        partial void OnPlatformReceivingSymbolRootChanging(string value);
        partial void OnPlatformReceivingSymbolRootChanged();
        /// <summary>
        /// There are no comments for Property BloombergSymbolRoot in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BloombergSymbolRoot
        {
            get
            {
                return this._BloombergSymbolRoot;
            }
            set
            {
                this.OnBloombergSymbolRootChanging(value);
                this.ReportPropertyChanging("BloombergSymbolRoot");
                this._BloombergSymbolRoot = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("BloombergSymbolRoot");
                this.OnBloombergSymbolRootChanged();
            }
        }
        private string _BloombergSymbolRoot;
        partial void OnBloombergSymbolRootChanging(string value);
        partial void OnBloombergSymbolRootChanged();
        /// <summary>
        /// There are no comments for Property PlatformSendingSymbolRoot in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlatformSendingSymbolRoot
        {
            get
            {
                return this._PlatformSendingSymbolRoot;
            }
            set
            {
                this.OnPlatformSendingSymbolRootChanging(value);
                this.ReportPropertyChanging("PlatformSendingSymbolRoot");
                this._PlatformSendingSymbolRoot = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PlatformSendingSymbolRoot");
                this.OnPlatformSendingSymbolRootChanged();
            }
        }
        private string _PlatformSendingSymbolRoot;
        partial void OnPlatformSendingSymbolRootChanging(string value);
        partial void OnPlatformSendingSymbolRootChanged();
        /// <summary>
        /// There are no comments for Property PriceMultiplier in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceMultiplier
        {
            get
            {
                return this._PriceMultiplier;
            }
            set
            {
                this.OnPriceMultiplierChanging(value);
                this.ReportPropertyChanging("PriceMultiplier");
                this._PriceMultiplier = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PriceMultiplier");
                this.OnPriceMultiplierChanged();
            }
        }
        private decimal _PriceMultiplier;
        partial void OnPriceMultiplierChanging(decimal value);
        partial void OnPriceMultiplierChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
}
