package activemq.ui;

import activemq.broker.BrokerConfiguration;

import javax.swing.JDialog;

/**
 *
 */
@SuppressWarnings("serial")
public class ConfigurationPanelForm extends javax.swing.JPanel {

    private JDialog dialog;
    private BrokerConfiguration configuration;
    private IConfigurable configurable;
    private boolean updated;

    /** Creates new form ConfigurationPanelForm */
    public ConfigurationPanelForm() {
        initComponents();
        configuration = new BrokerConfiguration();
    }
    /** Creates new form ConfigurationPanelForm */
    public ConfigurationPanelForm(IConfigurable configurable) {
        setConfigurable(configurable);
        if (configurable.getConfiguration() == null) {
            configuration = new BrokerConfiguration();
            // Setup the Quantys defaults
            configuration.setServerName("amqmktdata");
            configuration.setJmsPort(63636);
            configuration.setJmxPort(9393);
        } else {
            configuration = configurable.getConfiguration();
        }
        initComponents();
    }

    /**
     * @param configurable the configurable to set
     */
    public void setConfigurable(IConfigurable configurable) {
        this.configurable = configurable;
    }

    public BrokerConfiguration getConfiguration() {
        if (configuration == null && configurable != null) {
            configuration = configurable.getConfiguration();
        }
        return configuration;
    }

    public void setConfiguration(BrokerConfiguration config) {
        this.configuration = config;
    }

    public JDialog getDialog() {
        return dialog;
    }

    public void setDialog(JDialog dialog) {
        this.dialog = dialog;
    }

    private void closeDialog(java.awt.event.ActionEvent evt) {
        if ("Cancel".equals(evt.getActionCommand())) {
            System.out.println("Cancel Event");
        }
        if (dialog != null) {
            dialog.dispose();
        }
        if (updated) {
            configurable.configurationUpdated();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        javax.swing.JLabel serverNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel jmsPortLabel = new javax.swing.JLabel();
        javax.swing.JLabel jmxPortLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        serverNameField = new javax.swing.JTextField();
        jmsPortField = activemq.ui.util.FormCreationHelper.createNumericField(0);
        jmxPortField = activemq.ui.util.FormCreationHelper.createNumericField(0);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(activemq.ActiveMQMonitor.class).getContext().getResourceMap(ConfigurationPanelForm.class);
        setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.insideBorder.insideBorder.title"))))); // NOI18N
        setName("Form"); // NOI18N

        serverNameLabel.setText(resourceMap.getString("serverNameLabel.text")); // NOI18N
        serverNameLabel.setName("serverNameLabel"); // NOI18N

        jmsPortLabel.setText(resourceMap.getString("jmsPortLabel.text")); // NOI18N
        jmsPortLabel.setName("jmsPortLabel"); // NOI18N

        jmxPortLabel.setText(resourceMap.getString("jmxPortLabel.text")); // NOI18N
        jmxPortLabel.setName("jmxPortLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(activemq.ActiveMQMonitor.class).getContext().getActionMap(ConfigurationPanelForm.class, this);
        applyButton.setAction(actionMap.get("applyValues")); // NOI18N
        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        serverNameField.setName("serverNameField"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${configuration.serverName}"), serverNameField, org.jdesktop.beansbinding.BeanProperty.create("text_ON_ACTION_OR_FOCUS_LOST"), ""); // NOI18N
        bindingGroup.addBinding(binding);

        jmsPortField.setName("jmsPortField"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${configuration.jmsPort}"), jmsPortField, org.jdesktop.beansbinding.BeanProperty.create("text_ON_ACTION_OR_FOCUS_LOST"));
        bindingGroup.addBinding(binding);

        jmxPortField.setName("jmxPortField"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${configuration.jmxPort}"), jmxPortField, org.jdesktop.beansbinding.BeanProperty.create("text_ON_ACTION_OR_FOCUS_LOST"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(serverNameLabel)
                                                .addComponent(jmsPortLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(serverNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jmxPortField, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jmsPortField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))))
                                                                .addComponent(jmxPortLabel)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(applyButton)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(okButton)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(cancelButton)))
                                                                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(serverNameLabel)
                                .addComponent(serverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jmsPortLabel)
                                        .addComponent(jmsPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jmxPortLabel)
                                                .addComponent(jmxPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(applyButton)
                                                        .addComponent(okButton)
                                                        .addComponent(cancelButton))
                                                        .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        closeDialog(evt);

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if ("Apply".equals(evt.getActionCommand())) {
            System.out.println("Apply Button");
        }
        configurable.setConfiguration(configuration);
        updated = true;
    }//GEN-LAST:event_applyButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        applyButtonActionPerformed(evt);
        closeDialog(evt);
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField jmsPortField;
    private javax.swing.JTextField jmxPortField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField serverNameField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
