package com.fftw.bfa.admin.seam.model;
// Generated Jan 10, 2008 5:29:55 PM by Hibernate Tools 3.2.0.b10

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FuturesSymbolMapping generated by hbm2java
 */
@Entity
@Table(name = "FUTURES_SYMBOL_MAPPING", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PLATFORM_ID", "PLATFORM_SYMBOL"}))
public class FuturesSymbolMapping implements java.io.Serializable {

	private long id;
	private ProductCode productCode;
	private Platform platform;
	private String platformSymbol;
	private String bloombergSymbol;
	private BigDecimal multiplier;
	private String description;

	public FuturesSymbolMapping() {
	}

	public FuturesSymbolMapping(long id, ProductCode productCode,
			Platform platform, String platformSymbol, String bloombergSymbol,
			BigDecimal multiplier) {
		this.id = id;
		this.productCode = productCode;
		this.platform = platform;
		this.platformSymbol = platformSymbol;
		this.bloombergSymbol = bloombergSymbol;
		this.multiplier = multiplier;
	}
	public FuturesSymbolMapping(long id, ProductCode productCode,
			Platform platform, String platformSymbol, String bloombergSymbol,
			BigDecimal multiplier, String description) {
		this.id = id;
		this.productCode = productCode;
		this.platform = platform;
		this.platformSymbol = platformSymbol;
		this.bloombergSymbol = bloombergSymbol;
		this.multiplier = multiplier;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLOOMBERG_SECTOR", nullable = false)
	@NotNull
	public ProductCode getProductCode() {
		return this.productCode;
	}

	public void setProductCode(ProductCode productCode) {
		this.productCode = productCode;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLATFORM_ID", nullable = false)
	@NotNull
	public Platform getPlatform() {
		return this.platform;
	}

	public void setPlatform(Platform platform) {
		this.platform = platform;
	}

	@Column(name = "PLATFORM_SYMBOL", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getPlatformSymbol() {
		return this.platformSymbol;
	}

	public void setPlatformSymbol(String platformSymbol) {
		this.platformSymbol = platformSymbol;
	}

	@Column(name = "BLOOMBERG_SYMBOL", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getBloombergSymbol() {
		return this.bloombergSymbol;
	}

	public void setBloombergSymbol(String bloombergSymbol) {
		this.bloombergSymbol = bloombergSymbol;
	}

	@Column(name = "MULTIPLIER", nullable = false, precision = 10, scale = 3)
	@NotNull
	public BigDecimal getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(BigDecimal multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "description", length = 50)
	@Length(max = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
