package com.fftw.bfa.admin.seam.model;
// Generated Jan 10, 2008 5:29:55 PM by Hibernate Tools 3.2.0.b10

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * MarketCalendar generated by hbm2java
 */
@Entity
@Table(name = "MARKET_CALENDAR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MARKET_ID", "CLOSED_ON"}))
public class MarketCalendar implements java.io.Serializable {

	private long id;
	private String marketId;
	private Date closedOn;
	private String description;

	public MarketCalendar() {
	}

	public MarketCalendar(long id, String marketId, Date closedOn) {
		this.id = id;
		this.marketId = marketId;
		this.closedOn = closedOn;
	}
	public MarketCalendar(long id, String marketId, Date closedOn,
			String description) {
		this.id = id;
		this.marketId = marketId;
		this.closedOn = closedOn;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "MARKET_ID", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getMarketId() {
		return this.marketId;
	}

	public void setMarketId(String marketId) {
		this.marketId = marketId;
	}

	@Column(name = "CLOSED_ON", nullable = false, length = 23)
	@NotNull
	public Date getClosedOn() {
		return this.closedOn;
	}

	public void setClosedOn(Date closedOn) {
		this.closedOn = closedOn;
	}

	@Column(name = "DESCRIPTION", length = 50)
	@Length(max = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
