package com.fftw.bfa.admin.seam.model;
// Generated Jan 10, 2008 5:29:55 PM by Hibernate Tools 3.2.0.b10

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ProductCode generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_CODE")
public class ProductCode implements java.io.Serializable {

	private String textCode;
	private short productCode;
	private String description;
	private Set<FuturesSymbolMapping> futuresSymbolMappings = new HashSet<FuturesSymbolMapping>(
			0);

	public ProductCode() {
	}

	public ProductCode(String textCode, short productCode, String description) {
		this.textCode = textCode;
		this.productCode = productCode;
		this.description = description;
	}
	public ProductCode(String textCode, short productCode, String description,
			Set<FuturesSymbolMapping> futuresSymbolMappings) {
		this.textCode = textCode;
		this.productCode = productCode;
		this.description = description;
		this.futuresSymbolMappings = futuresSymbolMappings;
	}

	@Id
	@Column(name = "TEXT_CODE", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getTextCode() {
		return this.textCode;
	}

	public void setTextCode(String textCode) {
		this.textCode = textCode;
	}

	@Column(name = "PRODUCT_CODE", nullable = false)
	@NotNull
	public short getProductCode() {
		return this.productCode;
	}

	public void setProductCode(short productCode) {
		this.productCode = productCode;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "productCode")
	public Set<FuturesSymbolMapping> getFuturesSymbolMappings() {
		return this.futuresSymbolMappings;
	}

	public void setFuturesSymbolMappings(
			Set<FuturesSymbolMapping> futuresSymbolMappings) {
		this.futuresSymbolMappings = futuresSymbolMappings;
	}

}
