package com.fftw.bfa.admin.seam.model;
// Generated Jan 10, 2008 5:29:55 PM by Hibernate Tools 3.2.0.b10

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TradingStrategy generated by hbm2java
 */
@Entity
@Table(name = "TRADING_STRATEGY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PLATFORM_ID", "FixTAG", "TagValue"}))
public class TradingStrategy implements java.io.Serializable {

	private long id;
	private Platform platform;
	private short fixTag;
	private String tagValue;
	private String bloombergAccount;
	private String bloombergStrategy;

	public TradingStrategy() {
	}

	public TradingStrategy(long id, Platform platform, short fixTag,
			String tagValue) {
		this.id = id;
		this.platform = platform;
		this.fixTag = fixTag;
		this.tagValue = tagValue;
	}
	public TradingStrategy(long id, Platform platform, short fixTag,
			String tagValue, String bloombergAccount, String bloombergStrategy) {
		this.id = id;
		this.platform = platform;
		this.fixTag = fixTag;
		this.tagValue = tagValue;
		this.bloombergAccount = bloombergAccount;
		this.bloombergStrategy = bloombergStrategy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@NotNull
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLATFORM_ID", nullable = false)
	@NotNull
	public Platform getPlatform() {
		return this.platform;
	}

	public void setPlatform(Platform platform) {
		this.platform = platform;
	}

	@Column(name = "FixTAG", nullable = false)
	@NotNull
	public short getFixTag() {
		return this.fixTag;
	}

	public void setFixTag(short fixTag) {
		this.fixTag = fixTag;
	}

	@Column(name = "TagValue", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTagValue() {
		return this.tagValue;
	}

	public void setTagValue(String tagValue) {
		this.tagValue = tagValue;
	}

	@Column(name = "BloombergAccount", length = 10)
	@Length(max = 10)
	public String getBloombergAccount() {
		return this.bloombergAccount;
	}

	public void setBloombergAccount(String bloombergAccount) {
		this.bloombergAccount = bloombergAccount;
	}

	@Column(name = "BloombergStrategy", length = 50)
	@Length(max = 50)
	public String getBloombergStrategy() {
		return this.bloombergStrategy;
	}

	public void setBloombergStrategy(String bloombergStrategy) {
		this.bloombergStrategy = bloombergStrategy;
	}

}
