USE [BADB]
GO
/****** Object:  Table [dbo].[TRADE_RECORD]    Script Date: 01/14/2008 09:11:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRADE_RECORD](
	[TRADE_RECORD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[TRADE_SEQ_NUM] [bigint] NOT NULL,
	[PLATFORM_ID] [varchar](5) COLLATE Latin1_General_BIN NOT NULL,
	[EXEC_ID] [varchar](50) COLLATE Latin1_General_BIN NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[SECURITY_ID_FLAG] [smallint] NOT NULL,
	[SECURITY_ID] [varchar](24) COLLATE Latin1_General_BIN NOT NULL,
	[TRADER_NAME] [varchar](8) COLLATE Latin1_General_BIN NULL,
	[SIDE] [smallint] NOT NULL,
	[QUANTITY] [decimal](20, 2) NOT NULL,
	[PRICE_DISPLAY] [smallint] NOT NULL,
	[PRICE] [decimal](15, 8) NOT NULL,
	[SETTLE_DATE] [datetime] NOT NULL,
	[ACCOUNT] [varchar](10) COLLATE Latin1_General_BIN NOT NULL,
	[PRODUCT_CODE] [smallint] NOT NULL,
	[SOURCE_CODE] [smallint] NOT NULL,
	[BROKER] [varchar](50) COLLATE Latin1_General_BIN NOT NULL,
	[PRIME_BROKER] [varchar](10) COLLATE Latin1_General_BIN NOT NULL,
	[TICKET_NUMBER] [int] NOT NULL CONSTRAINT [DF_TRADE_RECORD_TICKET_NUMBER]  DEFAULT ((0)),
	[RETURN_CODE] [smallint] NULL,
	[ERROR_MSG] [varchar](50) COLLATE Latin1_General_BIN NULL,
	[ACK_RECEIVED] [datetime] NULL,
	[ACCEPT_REJECT_RECEIVED] [datetime] NULL,
	[PROCESSING_STATUS] [varchar](30) COLLATE Latin1_General_BIN NULL,
	[TRADING_STRATEGY] [varchar](50) COLLATE Latin1_General_BIN NULL,
	[TRANS_CODE] [varchar](1) COLLATE Latin1_General_BIN NULL,
	[LAST_UPDATED] [datetime] NOT NULL,
 CONSTRAINT [TRKEY] PRIMARY KEY CLUSTERED 
(
	[TRADE_RECORD_ID] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [BADB]
GO
ALTER TABLE [dbo].[TRADE_RECORD]  WITH CHECK ADD  CONSTRAINT [FK_TRADE_RECORD_PLATFORM] FOREIGN KEY([PLATFORM_ID])
REFERENCES [dbo].[PLATFORM] ([PLATFORM_ID])